### ISSUE TITLE
Fdroid release.

### ISSUE THREAD

**Issue by 4mohamedaliii** [DeveshRx/Text-Master-OCR#2]
Since the app is OpenSource it should be on f-droid repo because people search for OpenSource apps there.

**Comment by strider72** [comment]
I believe it's not because it uses Google APIs for the OCR

**Comment by DeveshRx** [comment]
Text Master OCR App uses Google APIs so it's not possible to publish on f-droid.

**Comment by Darthagnon** [comment]
[IzzyOnDroid/IzzySoft](https://apt.izzysoft.de/)? I think they're slightly less demanding about "no Google"... (though on Reddit you said the OCR was offline...? Aren't all the Google APIs online?)
