### ISSUE TITLE
[Feature request] QR/barcode support?

### ISSUE THREAD

**Issue by Darthagnon** [DeveshRx/Text-Master-OCR#3]
Would it be possible to add a feature to decode QR codes and barcodes with this app? Google Lens does this, and it would be nice to have a complete replacement!

**Comment by DeveshRx** [comment]
Aim is to build OCR App but i'm already working on QR Code App project so i might integrate it into Text Master in future if possible.

**Comment by DeveshRx** [comment]
For Creating & Scanning QR Code, here is Open-source app:

https://play.google.com/store/apps/details?id=devesh.ephrine.qr.code

https://github.com/DeveshRx/QR-Lite

**Comment by DeveshRx** [comment]
For Creating & Scanning QR Code, here is Open-source app:

https://play.google.com/store/apps/details?id=devesh.ephrine.qr.code

https://github.com/DeveshRx/QR-Lite
