### ISSUE TITLE
[Feature Request] Add ability (Android intent) to receive shared images.

### ISSUE THREAD

**Issue by eric72777** [DeveshRx/Text-Master-OCR#4]
**Feature Request**
It would be great if I could share a image from a web browser to Text-Master-OCR. Currently, the app does show up when I try to share an app.

**App Version**
Text Master OCR Version 1.0.0, phone on Android 12

**How to reproduce**
Open a web browser. Navigate to an image on the web browser. Long click the image, click the share icon. Text Master OCR is not an available app to share the image with.

**Comment by DeveshRx** [comment]
will work on this feature. 
Thanks for suggestion

**Comment by DeveshRx** [comment]
Feature added in Version [1.0.0.1](https://play.google.com/store/apps/details?id=devesh.app.ocr)
